/**
 * Mock data cho Doctor Portal
 */

// Thông tin bác sĩ hiện tại
export const MOCK_DOCTOR_PROFILE = {
    id: "DR-2024001",
    code: "BS-001",
    fullName: "BS. Nguyễn Văn Minh",
    email: "minh.nguyen@ehealth.vn",
    phone: "0909 123 456",
    departmentId: "DEPT-001",
    department: "Khoa Nội Tổng Quát",
    departmentName: "Khoa Nội Tổng Quát",
    specialization: "Nội tổng quát",
    title: "Bác sĩ chuyên khoa II",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuDe1rc71Y7tDtvAIsivpcpjQnKf7Ilt1nM6EZmYVYwkjQ-EDUXOe4tp0zVG61kptcoC6rC85SSecuu1xYemUygIvJDm8KszhMZUbcFpTR6dWes4qn3vnzPhyZEcS_-y074gFSVdid3bgZxh7ycwM241VD8_uAZbwQTHfnV90tbuM2fsxfhnIH-uMlxnBfmBBrBLB9P_hMor36bwfYbJDUoRXfuHo8jL5YSPHxsvbe1JWyNVw6E1zVymCev-31CXVv-mC3ZLkWowxCqU",
    rating: 4.8,
    reviewCount: 156,
};

// Thống kê trang chủ bác sĩ
export const MOCK_DOCTOR_DASHBOARD_STATS = {
    todayExams: 18,
    totalExamsToday: 25,
    progressPercent: 72,
    waitingPatients: 4,
    avgWaitTime: 15, // phút
    personalRevenue: 12500000, // VND
    revenueChange: 5, // %
};

// Thống kê lượt khám tuần
export const MOCK_WEEKLY_EXAM_STATS = [
    { day: "T2", count: 12, percentage: 40 },
    { day: "T3", count: 18, percentage: 55 },
    { day: "T4", count: 25, percentage: 75 },
    { day: "T5", count: 20, percentage: 60 },
    { day: "T6", count: 22, percentage: 65 },
    { day: "T7", count: 10, percentage: 30 },
    { day: "CN", count: 5, percentage: 20 },
];

// Lịch trình hôm nay
export const MOCK_TODAY_SCHEDULE = [
    {
        id: "SCH-001",
        time: "08:00",
        title: "Giao ban khoa",
        location: "Phòng họp A1",
        duration: "45 phút",
        type: "meeting",
        status: "completed",
    },
    {
        id: "SCH-002",
        time: "09:00",
        title: "Khám bệnh (25 ca)",
        location: "Phòng khám 302",
        duration: "3 giờ",
        type: "examination",
        status: "ongoing",
    },
    {
        id: "SCH-003",
        time: "12:00",
        title: "Nghỉ trưa",
        location: "",
        duration: "1 giờ 30 phút",
        type: "break",
        status: "upcoming",
    },
    {
        id: "SCH-004",
        time: "13:30",
        title: "Hội chẩn ca khó",
        location: "Trực tuyến (Zoom)",
        duration: "1 giờ",
        type: "consultation",
        status: "upcoming",
    },
];

// Thông báo từ bệnh viện
export const MOCK_HOSPITAL_ANNOUNCEMENTS = [
    {
        id: "ANN-001",
        title: "Cập nhật phác đồ điều trị Sốt xuất huyết",
        content: "Ban hành hướng dẫn chẩn đoán và điều trị sốt xuất huyết Dengue theo quyết định mới nhất của Bộ Y Tế. Đề nghị các bác sĩ cập nhật...",
        time: "10:30 AM",
        department: "Phòng Kế hoạch tổng hợp",
        type: "urgent",
    },
    {
        id: "ANN-002",
        title: "Lịch bảo trì hệ thống E-Health",
        content: "Hệ thống sẽ tạm ngưng để bảo trì định kỳ từ 22:00 đến 23:00 ngày 20/11/2023. Vui lòng lưu dữ liệu trước thời gian này.",
        time: "08:00 AM",
        department: "Ban CNTT",
        type: "info",
    },
];

// Hàng đợi bệnh nhân
export const MOCK_PATIENT_QUEUE = [
    {
        id: "BN-24881",
        queueNumber: 11,
        fullName: "Phạm Thị Lan",
        gender: "Nữ",
        age: 42,
        phone: "0909 *** 888",
        checkInTime: "10:00 AM",
        reason: "Sốt cao, ho khan, đau họng kéo dài 2 ngày.",
        status: "examining",
        avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPJ5L91y7LNqP6VdpYAgXbcVJlHcY_JyDaglGe5y00s6vMTdWi5zm4zLblp5qdPYv3voBG0PqKwJu_XgSQjpryGzRKz26YplL9X0ADnJwzWpNJLSE9OXYrLZoFbyU23rdIFs0Ql4doDlCzYX-UpqaczJ6DcnBVqCDb0CYoGc5-hoojPFYJIIhZ3spv_ri2tCSvKTWqih8Xh7neNn7rPVUnZBXe3jyZo-cehfBDhWlyqRE4nUUT5y9O667LZInqlyFTKJwz8cAicVI_",
        birthDate: "12/05/1982",
        allergies: ["Penicillin"],
        medicalHistory: ["Viêm dạ dày cấp (03/2023)", "Viêm họng (10/2022)"],
    },
    {
        id: "BN-24902",
        queueNumber: 12,
        fullName: "Trần Văn Bình",
        gender: "Nam",
        age: 56,
        phone: "0912 *** 456",
        checkInTime: "10:15 AM",
        reason: "Tái khám huyết áp, chóng mặt nhẹ.",
        status: "waiting",
        avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCHeoRdtmGNNzzPY4Q1tH3dM1aVrB-27BycMwXrXpcJN5xEE6rUaKZkrX2Ch8KkVGPOQIDX_d6Fqa1H0kkzIs4-eksBX8bfHmFSJn0myb4AlJy7-HMNCG3bnf8n05LY_GJBQFxO1dJ_PmK9YXwA047T4eGOqwFerCKG2xJ5MDCEI2MfwLRbJsV6NCruw77k2mROhyBJtxi-TpmE56NmuQLo6Pf9T5P_gCMkiDLsfdMDlSWJCoEBjGZE1MLHgZsKi3qBbRgZw2-6yTsk",
        birthDate: "22/08/1968",
        allergies: [],
        medicalHistory: ["Tăng huyết áp (2020)"],
    },
    {
        id: "BN-24915",
        queueNumber: 13,
        fullName: "Lê Thị Mai",
        gender: "Nữ",
        age: 28,
        phone: "0987 *** 321",
        checkInTime: "10:30 AM",
        reason: "Đau thượng vị, ợ hơi, khó tiêu.",
        status: "waiting",
        avatar: "",
        birthDate: "15/03/1996",
        allergies: [],
        medicalHistory: [],
    },
    {
        id: "BN-24933",
        queueNumber: 14,
        fullName: "Hoàng Văn Nam",
        gender: "Nam",
        age: 35,
        phone: "0903 *** 789",
        checkInTime: "10:45 AM",
        reason: "Kiểm tra sức khỏe định kỳ.",
        status: "waiting",
        avatar: "",
        birthDate: "08/11/1989",
        allergies: [],
        medicalHistory: [],
    },
];

// Thống kê hàng đợi
export const MOCK_QUEUE_STATS = {
    remaining: 14,
    total: 45,
    waiting: 13,
    examining: 1,
    completed: 31,
    cancelled: 2,
    avgWaitTime: 15, // phút
    shiftEnd: "11:30",
    estimatedTimeLeft: "2h30p",
};

// Lịch hẹn
export const MOCK_APPOINTMENTS = [
    {
        id: "APT-001",
        patientId: "BN-24881",
        patientName: "Phạm Thị Lan",
        patientAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPJ5L91y7LNqP6VdpYAgXbcVJlHcY_JyDaglGe5y00s6vMTdWi5zm4zLblp5qdPYv3voBG0PqKwJu_XgSQjpryGzRKz26YplL9X0ADnJwzWpNJLSE9OXYrLZoFbyU23rdIFs0Ql4doDlCzYX-UpqaczJ6DcnBVqCDb0CYoGc5-hoojPFYJIIhZ3spv_ri2tCSvKTWqih8Xh7neNn7rPVUnZBXe3jyZo-cehfBDhWlyqRE4nUUT5y9O667LZInqlyFTKJwz8cAicVI_",
        date: "2024-10-24",
        startTime: "09:00",
        endTime: "10:00",
        type: "in_person",
        reason: "Tái khám: Sốt siêu vi",
        status: "confirmed",
        dayOfWeek: 2,
    },
    {
        id: "APT-002",
        patientId: "BN-24902",
        patientName: "Trần Văn Bình",
        patientAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCHeoRdtmGNNzzPY4Q1tH3dM1aVrB-27BycMwXrXpcJN5xEE6rUaKZkrX2Ch8KkVGPOQIDX_d6Fqa1H0kkzIs4-eksBX8bfHmFSJn0myb4AlJy7-HMNCG3bnf8n05LY_GJBQFxO1dJ_PmK9YXwA047T4eGOqwFerCKG2xJ5MDCEI2MfwLRbJsV6NCruw77k2mROhyBJtxi-TpmE56NmuQLo6Pf9T5P_gCMkiDLsfdMDlSWJCoEBjGZE1MLHgZsKi3qBbRgZw2-6yTsk",
        date: "2024-10-24",
        startTime: "10:00",
        endTime: "10:30",
        type: "online",
        reason: "Tư vấn huyết áp",
        status: "confirmed",
        dayOfWeek: 2,
    },
    {
        id: "APT-003",
        patientId: "BN-24915",
        patientName: "Lê Thị Mai",
        patientAvatar: "",
        date: "2024-10-24",
        startTime: "10:30",
        endTime: "11:30",
        type: "in_person",
        reason: "Khám tiêu hóa",
        status: "confirmed",
        dayOfWeek: 2,
    },
];

// Yêu cầu lịch hẹn chờ xác nhận
export const MOCK_PENDING_APPOINTMENTS = [
    {
        id: "REQ-001",
        patientId: "BN-NEW-001",
        patientName: "Nguyễn Thị Hương",
        patientAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPJ5L91y7LNqP6VdpYAgXbcVJlHcY_JyDaglGe5y00s6vMTdWi5zm4zLblp5qdPYv3voBG0PqKwJu_XgSQjpryGzRKz26YplL9X0ADnJwzWpNJLSE9OXYrLZoFbyU23rdIFs0Ql4doDlCzYX-UpqaczJ6DcnBVqCDb0CYoGc5-hoojPFYJIIhZ3spv_ri2tCSvKTWqih8Xh7neNn7rPVUnZBXe3jyZo-cehfBDhWlyqRE4nUUT5y9O667LZInqlyFTKJwz8cAicVI_",
        gender: "Nữ",
        age: 32,
        isReturning: true,
        date: "Ngày mai",
        startTime: "09:00",
        endTime: "09:30",
        type: "online",
        reason: "Tôi bị đau đầu kéo dài 3 ngày nay, đã uống Panadol nhưng không đỡ...",
    },
    {
        id: "REQ-002",
        patientId: "BN-NEW-002",
        patientName: "Trần Minh Tuấn",
        patientAvatar: "",
        gender: "Nam",
        age: 45,
        isReturning: false,
        date: "26/10",
        startTime: "14:30",
        endTime: "15:00",
        type: "in_person",
        reason: "",
    },
    {
        id: "REQ-003",
        patientId: "BN-NEW-003",
        patientName: "Phạm Lan Anh",
        patientAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBQSbUZJvojdr2IwTf3hOBplzpOA9ZBePJ18mLI_DIUeGf8Gtg6XoTNRnsPTacX6QniCBY4q0GUrytzc27YUweeQe0FPDeEJXd1U2XGfCfiOs_geb4x5ndHM-YV63ddXQ1vlapLc-cym1TB8-vNr7rhUBkrNYKRY2qbSD7nWyxjHzCjoUFSz9oZKhn5PtqTYtpaTLCXNlKki2MFOsVbWOYeZU0ivhOeRpACb3WQVkNufm51k5FdNfE6oG1PLh9UG34vELURmR6Z7Z_B",
        gender: "Nữ",
        age: 24,
        isReturning: false,
        date: "27/10",
        startTime: "10:00",
        endTime: "10:30",
        type: "online",
        reason: "",
    },
];

// Danh sách đơn thuốc của bác sĩ
export const MOCK_DOCTOR_PRESCRIPTIONS = [
    {
        id: "DT-24881",
        patientId: "BN-24881",
        patientName: "Phạm Thị Lan",
        patientAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPJ5L91y7LNqP6VdpYAgXbcVJlHcY_JyDaglGe5y00s6vMTdWi5zm4zLblp5qdPYv3voBG0PqKwJu_XgSQjpryGzRKz26YplL9X0ADnJwzWpNJLSE9OXYrLZoFbyU23rdIFs0Ql4doDlCzYX-UpqaczJ6DcnBVqCDb0CYoGc5-hoojPFYJIIhZ3spv_ri2tCSvKTWqih8Xh7neNn7rPVUnZBXe3jyZo-cehfBDhWlyqRE4nUUT5y9O667LZInqlyFTKJwz8cAicVI_",
        patientAge: 42,
        patientGender: "Nữ",
        diagnosis: "Viêm họng cấp (J02.9)",
        date: "12/05/2024 - 10:45",
        medicines: "Paracetamol 500mg, Alpha Choay, Vitamin C",
        status: "pending",
    },
    {
        id: "DT-24879",
        patientId: "BN-24902",
        patientName: "Trần Văn Bình",
        patientAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCHeoRdtmGNNzzPY4Q1tH3dM1aVrB-27BycMwXrXpcJN5xEE6rUaKZkrX2Ch8KkVGPOQIDX_d6Fqa1H0kkzIs4-eksBX8bfHmFSJn0myb4AlJy7-HMNCG3bnf8n05LY_GJBQFxO1dJ_PmK9YXwA047T4eGOqwFerCKG2xJ5MDCEI2MfwLRbJsV6NCruw77k2mROhyBJtxi-TpmE56NmuQLo6Pf9T5P_gCMkiDLsfdMDlSWJCoEBjGZE1MLHgZsKi3qBbRgZw2-6yTsk",
        patientAge: 56,
        patientGender: "Nam",
        diagnosis: "Tăng huyết áp (I10)",
        date: "12/05/2024 - 09:30",
        medicines: "Amlodipin 5mg, Atorvastatin 20mg",
        status: "completed",
    },
    {
        id: "DT-24875",
        patientId: "BN-24915",
        patientName: "Lê Thị Mai",
        patientAvatar: "",
        patientAge: 28,
        patientGender: "Nữ",
        diagnosis: "Viêm dạ dày (K29)",
        date: "12/05/2024 - 09:00",
        medicines: "Phosphalugel, Omeprazol 20mg",
        status: "completed",
    },
    {
        id: "DT-24860",
        patientId: "BN-24800",
        patientName: "Nguyễn Thu Hà",
        patientAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBQSbUZJvojdr2IwTf3hOBplzpOA9ZBePJ18mLI_DIUeGf8Gtg6XoTNRnsPTacX6QniCBY4q0GUrytzc27YUweeQe0FPDeEJXd1U2XGfCfiOs_geb4x5ndHM-YV63ddXQ1vlapLc-cym1TB8-vNr7rhUBkrNYKRY2qbSD7nWyxjHzCjoUFSz9oZKhn5PtqTYtpaTLCXNlKki2MFOsVbWOYeZU0ivhOeRpACb3WQVkNufm51k5FdNfE6oG1PLh9UG34vELURmR6Z7Z_B",
        patientAge: 35,
        patientGender: "Nữ",
        diagnosis: "Rối loạn tiền đình (H81)",
        date: "11/05/2024 - 16:15",
        medicines: "Betaserc 24mg, Tanganil 500mg",
        status: "completed",
    },
    {
        id: "DT-24855",
        patientId: "BN-24855",
        patientName: "Hoàng Văn Nam",
        patientAvatar: "",
        patientAge: 60,
        patientGender: "Nam",
        diagnosis: "Đái tháo đường type 2 (E11)",
        date: "11/05/2024 - 14:20",
        medicines: "Metformin 850mg, Gliclazide 30mg",
        status: "cancelled",
    },
];

// Hồ sơ bệnh án - Danh sách bệnh nhân
export const MOCK_PATIENT_RECORDS = [
    {
        id: "BN-24881",
        fullName: "Phạm Thị Lan",
        gender: "Nữ",
        age: 42,
        phone: "0909 *** 888",
        address: "Hà Nội",
        birthDate: "12/05/1982",
        avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBQSbUZJvojdr2IwTf3hOBplzpOA9ZBePJ18mLI_DIUeGf8Gtg6XoTNRnsPTacX6QniCBY4q0GUrytzc27YUweeQe0FPDeEJXd1U2XGfCfiOs_geb4x5ndHM-YV63ddXQ1vlapLc-cym1TB8-vNr7rhUBkrNYKRY2qbSD7nWyxjHzCjoUFSz9oZKhn5PtqTYtpaTLCXNlKki2MFOsVbWOYeZU0ivhOeRpACb3WQVkNufm51k5FdNfE6oG1PLh9UG34vELURmR6Z7Z_B",
        lastVisit: "Hôm qua",
        currentDiagnosis: "Viêm họng cấp",
        status: "active",
        allergies: [{ name: "Penicillin", reaction: "Gây phát ban", year: "2018" }],
        familyHistory: ["Tiền sử gia đình có người bị hen suyễn"],
        medicalHistory: [
            {
                date: "Hôm qua",
                time: "10:00 AM",
                diagnosis: "Viêm họng cấp",
                icdCode: "J02.9",
                doctor: "BS. Nguyễn Văn Minh",
                department: "Nội tổng quát",
                symptoms: "Sốt nhẹ, ho khan, rát họng, người mệt mỏi.",
                treatment: "Kê đơn thuốc ngoại trú, dặn dò nghỉ ngơi.",
                isCurrent: true,
            },
            {
                date: "15/03/2023",
                time: "09:30 AM",
                diagnosis: "Viêm dạ dày cấp",
                icdCode: "K29",
                doctor: "BS. Lê Thị Hoa",
                department: "Tiêu hóa",
                symptoms: "Đau thượng vị, ợ hơi, buồn nôn.",
                treatment: "Nội soi, kê thuốc điều trị.",
                isCurrent: false,
            },
            {
                date: "10/11/2022",
                time: "",
                diagnosis: "Cảm cúm mùa",
                icdCode: "J11",
                doctor: "BS. Hương",
                department: "Tai Mũi Họng",
                symptoms: "",
                treatment: "Đã điều trị ngoại trú 5 ngày. Hồi phục tốt.",
                isCurrent: false,
            },
        ],
        labResults: [
            {
                id: "LAB-001",
                name: "Huyết học tổng quát",
                date: "15/05/2024",
                doctor: "BS. Minh",
                type: "pdf",
                result: "Bình thường",
            },
            {
                id: "LAB-002",
                name: "Nội soi dạ dày",
                date: "15/03/2023",
                doctor: "BS. Hoa",
                type: "image",
                result: "Viêm sung huyết",
            },
            {
                id: "LAB-003",
                name: "X-Quang Ngực thẳng",
                date: "10/11/2022",
                doctor: "BS. Nam",
                type: "image",
                result: "Bình thường",
            },
        ],
    },
    {
        id: "BN-24855",
        fullName: "Trần Văn Bình",
        gender: "Nam",
        age: 56,
        phone: "0912 *** 456",
        address: "Hà Nội",
        birthDate: "22/08/1968",
        avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCHeoRdtmGNNzzPY4Q1tH3dM1aVrB-27BycMwXrXpcJN5xEE6rUaKZkrX2Ch8KkVGPOQIDX_d6Fqa1H0kkzIs4-eksBX8bfHmFSJn0myb4AlJy7-HMNCG3bnf8n05LY_GJBQFxO1dJ_PmK9YXwA047T4eGOqwFerCKG2xJ5MDCEI2MfwLRbJsV6NCruw77k2mROhyBJtxi-TpmE56NmuQLo6Pf9T5P_gCMkiDLsfdMDlSWJCoEBjGZE1MLHgZsKi3qBbRgZw2-6yTsk",
        lastVisit: "15/05/2023",
        currentDiagnosis: "Tăng huyết áp vô căn",
        status: "active",
        allergies: [],
        familyHistory: [],
        medicalHistory: [],
        labResults: [],
    },
    {
        id: "BN-24840",
        fullName: "Lê Thị Mai",
        gender: "Nữ",
        age: 28,
        phone: "0987 *** 321",
        address: "Hà Nội",
        birthDate: "15/03/1996",
        avatar: "",
        lastVisit: "10/05/2023",
        currentDiagnosis: "Đau dạ dày",
        status: "active",
        allergies: [],
        familyHistory: [],
        medicalHistory: [],
        labResults: [],
    },
    {
        id: "BN-24792",
        fullName: "Nguyễn Thu Hà",
        gender: "Nữ",
        age: 35,
        phone: "0903 *** 789",
        address: "Hà Nội",
        birthDate: "08/11/1989",
        avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBPJ5L91y7LNqP6VdpYAgXbcVJlHcY_JyDaglGe5y00s6vMTdWi5zm4zLblp5qdPYv3voBG0PqKwJu_XgSQjpryGzRKz26YplL9X0ADnJwzWpNJLSE9OXYrLZoFbyU23rdIFs0Ql4doDlCzYX-UpqaczJ6DcnBVqCDb0CYoGc5-hoojPFYJIIhZ3spv_ri2tCSvKTWqih8Xh7neNn7rPVUnZBXe3jyZo-cehfBDhWlyqRE4nUUT5y9O667LZInqlyFTKJwz8cAicVI_",
        lastVisit: "20/04/2023",
        currentDiagnosis: "Khám sức khỏe định kỳ",
        status: "active",
        allergies: [],
        familyHistory: [],
        medicalHistory: [],
        labResults: [],
    },
];

// Thống kê báo cáo
export const MOCK_DOCTOR_REPORT_STATS = {
    totalExams: 245,
    totalExamsChange: 12,
    revenue: "45tr",
    revenueChange: 8,
    examsPerDay: 8.2,
    examsPerDayChange: 5,
    avgRating: 4.8,
    totalReviews: 156,
};

// Top bệnh lý thường gặp
export const MOCK_TOP_DISEASES = [
    { name: "Viêm họng cấp", icdCode: "J02.9", count: 45, percentage: 35, trend: "up" },
    { name: "Cảm cúm", icdCode: "J11", count: 32, percentage: 25, trend: "down" },
    { name: "Viêm dạ dày", icdCode: "K29", count: 28, percentage: 20, trend: "stable" },
    { name: "Tăng huyết áp", icdCode: "I10", count: 18, percentage: 12, trend: "up" },
    { name: "Rối loạn tiền đình", icdCode: "H81", count: 12, percentage: 8, trend: "stable" },
];

// Xu hướng khám theo tháng
export const MOCK_MONTHLY_EXAM_TREND = [
    { month: "T1", count: 180, percentage: 58 },
    { month: "T2", count: 195, percentage: 63 },
    { month: "T3", count: 210, percentage: 68 },
    { month: "T4", count: 225, percentage: 73 },
    { month: "T5", count: 245, percentage: 79 },
    { month: "T6", count: 220, percentage: 71 },
    { month: "T7", count: 235, percentage: 76 },
    { month: "T8", count: 250, percentage: 81 },
    { month: "T9", count: 265, percentage: 85 },
    { month: "T10", count: 280, percentage: 90 },
    { month: "T11", count: 290, percentage: 94 },
    { month: "T12", count: 310, percentage: 100 },
];
