version: "3.8"

services:
  backend:
    build: .
    container_name: be_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - postgres-db_default

networks:
  postgres-db_default:
    external: true
